config:
  credentials: []
  project_repos:
    github.com/ARGOeu/argo-scg:
      branch: master
      repo: https://github.com/ARGOeu/argo-scg.git
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ARGOeu/argo-scg git:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-emerald-gorilla.sh
        container: qc.acc_ready-auburn-shark
  QC.Doc:
    repos:
      github.com/ARGOeu/argo-scg find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-gold-bracke.sh
        container: qc.doc_smelly-thistle-walrus
      github.com/ARGOeu/argo-scg git:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-fuchsia-elephant.sh
        container: qc.doc_seedy-cardinal-wasp
      github.com/ARGOeu/argo-scg markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-ultramarine-bloodhound.sh
        container: qc.doc_flaky-rust-tarantula
  QC.Lic:
    repos:
      github.com/ARGOeu/argo-scg licensee:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-ultramarine-bobcat.sh
        container: qc.lic_geeky-tomato-caterpillar
  QC.Sec:
    repos:
      github.com/ARGOeu/argo-scg bandit:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-wisteria-gibbon.sh
        container: qc.sec_beady-green-terrier
  QC.Sty:
    repos:
      github.com/ARGOeu/argo-scg flake8:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-flax-wasp.sh
        container: qc.sty_stinky-scarlet-husky
  QC.Uni:
    repos:
      github.com/ARGOeu/argo-scg pytest:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-rose-hornet.sh
        container: qc.uni_scanty-malachite-corgi
  QC.Ver:
    repos:
      github.com/ARGOeu/argo-scg get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.homely-taupe-pig.sh
        container: qc.ver_baggy-rust-molly
timeout: 5400
